### ISSUE TITLE
Topics created via REST are not visible in the webclient without re-editing.

### ISSUE THREAD

**Issue by junes** [digitalmemex/dm4-gamechangers#2]
At the very moment all proposals and comments that are created via gamechanger's REST API need to be re-edited inside the DM webclient, before their labels get visible on the canvas and in the detail panel.

**Comment by thebohemian** [comment]
Fixed by e6055126665218a67a3e1485f480c73ec3529438

**Comment by thebohemian** [comment]
This has been fixed by commit ffe567d505d3fbdeecd2a503e70dcf0b5b8b24d0 which reworked the plugin to use the model-based store API.
